# src/analysis/business_insights.py
"""
Business intelligence insights: Pareto analysis, revenue concentration, and seasonality.

Analyses
--------
1. Pareto (80/20) Analysis
   Determines what percentage of customers drive 80% of revenue.
   In most retail businesses, 20% of customers generate 80% of revenue.
   Knowing this ratio justifies CLV-based targeting: a small group is disproportionately valuable.

2. Revenue Concentration (Lorenz Curve + Gini Coefficient)
   The Lorenz curve plots cumulative revenue share vs cumulative customer share.
   The Gini coefficient (0=perfectly equal, 1=perfectly concentrated) quantifies inequality.
   High Gini → targeting high-value customers has high leverage.

3. Monthly Revenue Trend
   Time-series view of revenue to understand seasonality, growth trends, and anomalies.
   Informs whether the CLV forecast horizon needs seasonal adjustment.

4. Customer Value Distribution
   Distribution of per-customer lifetime revenue with log scale.
   Shows the heavy-tailed nature of customer value — the justification for CLV modeling.

Outputs
-------
- reports/tables/pareto_summary.csv — revenue concentration statistics
- reports/figures/revenue_concentration_curve.png — Lorenz curve + Gini
- reports/figures/monthly_revenue_trend.png — monthly revenue time series
- reports/figures/customer_value_distribution.png — histogram of per-customer revenue
"""

from __future__ import annotations

import argparse
import logging
from pathlib import Path
from typing import Sequence

import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import numpy as np
import pandas as pd

LOGGER = logging.getLogger(__name__)


def setup_logging(level: str = "INFO") -> None:
    """Configure root-level console logging.

    Args:
        level: A string log level (e.g. ``"INFO"``, ``"DEBUG"``).
            Unrecognised values fall back to ``INFO``.
    """
    logging.basicConfig(
        level=getattr(logging, level.upper(), logging.INFO),
        format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
    )


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    """Parse CLI arguments for the business insights module.

    Args:
        argv: Optional list of CLI tokens.  Defaults to ``sys.argv[1:]``.

    Returns:
        Parsed :class:`argparse.Namespace` with ``transactions_path``,
        ``features_path``, and ``log_level``.
    """
    parser = argparse.ArgumentParser(description="Business intelligence insights.")
    parser.add_argument("--transactions-path", default="data/interim/transactions_clean.parquet")
    parser.add_argument("--features-path", default="data/processed/customer_features.parquet")
    parser.add_argument("--log-level", default="INFO")
    return parser.parse_args(argv)


def pareto_analysis(features: pd.DataFrame) -> dict:
    """
    Compute Pareto (80/20) concentration statistics.

    Returns a dict with:
    - pct_customers_for_80pct_revenue: % of customers who generate 80% of total revenue
    - pct_revenue_top_10pct: % of revenue generated by top 10% of customers
    - gini_coefficient: revenue inequality (0=equal, 1=maximally concentrated)
    - lorenz_x: cumulative customer percentile (for plotting)
    - lorenz_y: cumulative revenue percentile (for plotting)
    """
    revenue = features[["customer_id", "total_revenue"]].copy()
    revenue = revenue.sort_values("total_revenue", ascending=True).reset_index(drop=True)
    revenue["cum_revenue"] = revenue["total_revenue"].cumsum()
    revenue["cum_revenue_pct"] = revenue["cum_revenue"] / revenue["total_revenue"].sum() * 100
    revenue["cum_customer_pct"] = (np.arange(1, len(revenue) + 1)) / len(revenue) * 100

    # % of customers who generate 80% of revenue → find first customer where cumulative hits 80%
    idx_80 = np.searchsorted(revenue["cum_revenue_pct"].values, 80)
    pct_customers_for_80 = float(revenue.iloc[idx_80]["cum_customer_pct"])

    # % revenue from top 10% customers
    top10_threshold = int(np.floor(len(revenue) * 0.90))
    pct_revenue_top10 = float(100 - revenue.iloc[top10_threshold]["cum_revenue_pct"])

    # Gini coefficient from Lorenz curve
    x = revenue["cum_customer_pct"].values / 100
    y = revenue["cum_revenue_pct"].values / 100
    # Area under Lorenz curve (trapezoidal rule)
    lorenz_area = np.trapz(y, x)
    gini = float(1 - 2 * lorenz_area)

    return {
        "pct_customers_for_80pct_revenue": round(pct_customers_for_80, 1),
        "pct_revenue_top_10pct_customers": round(pct_revenue_top10, 1),
        "gini_coefficient": round(gini, 4),
        "lorenz_x": revenue["cum_customer_pct"].values,
        "lorenz_y": revenue["cum_revenue_pct"].values,
        "n_customers": len(revenue),
        "total_revenue": float(revenue["total_revenue"].sum()),
    }


def plot_revenue_concentration(pareto_stats: dict, output_path: Path) -> None:
    """Lorenz curve showing revenue concentration inequality."""
    x = pareto_stats["lorenz_x"]
    y = pareto_stats["lorenz_y"]
    gini = pareto_stats["gini_coefficient"]
    pct_cust = pareto_stats["pct_customers_for_80pct_revenue"]
    pct_rev_top10 = pareto_stats["pct_revenue_top_10pct_customers"]

    fig, axes = plt.subplots(1, 2, figsize=(13, 5))

    # Lorenz curve
    ax = axes[0]
    ax.plot([0, 100], [0, 100], "k--", linewidth=1.2, alpha=0.6, label="Perfect equality")
    ax.plot(x, y, color="#1565C0", linewidth=2.5, label=f"Revenue Lorenz curve (Gini={gini:.3f})")
    ax.fill_between(x, y, [xi for xi in x], alpha=0.2, color="#1565C0")

    # 80% revenue line
    ax.axhline(80, color="#E53935", linestyle="--", linewidth=1, alpha=0.7)
    ax.axvline(pct_cust, color="#E53935", linestyle="--", linewidth=1, alpha=0.7,
               label=f"{pct_cust:.0f}% of customers → 80% of revenue")
    ax.scatter([pct_cust], [80], color="#E53935", s=80, zorder=5)

    ax.set_xlabel("Cumulative % of Customers (sorted by revenue)", fontsize=11)
    ax.set_ylabel("Cumulative % of Revenue", fontsize=11)
    ax.set_title(f"Revenue Lorenz Curve (Gini = {gini:.3f})", fontsize=11, fontweight="bold")
    ax.legend(fontsize=9)
    ax.grid(alpha=0.3)
    ax.set_xlim(0, 100)
    ax.set_ylim(0, 100)

    # Revenue by percentile bars
    ax2 = axes[1]
    percentile_labels = ["Bottom 50%", "50–80%", "80–90%", "Top 10%"]
    percentile_revs = [
        y[int(len(y) * 0.50)],
        y[int(len(y) * 0.80)] - y[int(len(y) * 0.50)],
        y[int(len(y) * 0.90)] - y[int(len(y) * 0.80)],
        100 - y[int(len(y) * 0.90)],
    ]
    colors = ["#90CAF9", "#42A5F5", "#1E88E5", "#1565C0"]
    bars = ax2.bar(percentile_labels, percentile_revs, color=colors, edgecolor="white")
    for bar, val in zip(bars, percentile_revs):
        ax2.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.5,
                 f"{val:.1f}%", ha="center", va="bottom", fontsize=10, fontweight="bold")

    ax2.set_ylabel("% of Total Revenue", fontsize=11)
    ax2.set_title("Revenue Share by Customer Percentile", fontsize=11, fontweight="bold")
    ax2.grid(axis="y", alpha=0.3)
    ax2.set_ylim(0, max(percentile_revs) * 1.2)

    text = (f"Gini = {gini:.3f}  |  "
            f"Top 10% → {pct_rev_top10:.0f}% of revenue  |  "
            f"{pct_cust:.0f}% of customers → 80% of revenue")
    fig.suptitle(f"Revenue Concentration Analysis\n{text}", fontsize=12, fontweight="bold")
    fig.tight_layout()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    LOGGER.info("Revenue concentration curve → '%s'", str(output_path))


def plot_monthly_revenue(txn: pd.DataFrame, output_path: Path) -> None:
    """Monthly revenue trend with 3-month moving average."""
    txn = txn.copy()
    txn["month"] = txn["invoice_dt"].dt.to_period("M")
    monthly = txn.groupby("month")["revenue"].sum().reset_index()
    monthly["month_ts"] = monthly["month"].dt.to_timestamp()
    monthly["revenue_3m_ma"] = monthly["revenue"].rolling(3, min_periods=1).mean()

    fig, axes = plt.subplots(2, 1, figsize=(12, 7), sharex=True)

    # Revenue
    ax = axes[0]
    ax.fill_between(monthly["month_ts"], monthly["revenue"] / 1000,
                    alpha=0.3, color="#1565C0")
    ax.plot(monthly["month_ts"], monthly["revenue"] / 1000,
            color="#1565C0", linewidth=1.5, label="Monthly revenue")
    ax.plot(monthly["month_ts"], monthly["revenue_3m_ma"] / 1000,
            color="#C62828", linewidth=2.5, linestyle="--", label="3-month moving avg")
    ax.set_ylabel("Revenue (£ thousands)", fontsize=10)
    ax.set_title("Monthly Revenue Trend", fontsize=11, fontweight="bold")
    ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda v, _: f"£{v:,.0f}k"))
    ax.grid(alpha=0.3)
    ax.legend(fontsize=9)

    # Customer count
    monthly_customers = txn.groupby("month")["customer_id"].nunique().reset_index()
    monthly_customers["month_ts"] = monthly_customers["month"].dt.to_timestamp()

    ax2 = axes[1]
    ax2.bar(monthly_customers["month_ts"], monthly_customers["customer_id"],
            width=20, color="#43A047", alpha=0.7, label="Active customers")
    ax2.set_ylabel("Unique Active Customers", fontsize=10)
    ax2.set_xlabel("Month", fontsize=10)
    ax2.set_title("Monthly Active Customers", fontsize=11, fontweight="bold")
    ax2.grid(alpha=0.3)
    ax2.legend(fontsize=9)

    fig.suptitle("Business Performance — Monthly Revenue and Customer Activity",
                 fontsize=13, fontweight="bold")
    fig.tight_layout()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    LOGGER.info("Monthly revenue trend → '%s'", str(output_path))


def plot_customer_value_distribution(features: pd.DataFrame, output_path: Path) -> None:
    """Histogram of per-customer lifetime revenue (log-scale) showing the heavy tail."""
    rev = features["total_revenue"].clip(lower=1)

    fig, axes = plt.subplots(1, 2, figsize=(12, 4.5))

    # Linear scale
    ax = axes[0]
    ax.hist(rev, bins=50, color="#1565C0", edgecolor="white", alpha=0.8)
    ax.axvline(rev.mean(), color="#E53935", linestyle="--", linewidth=1.5,
               label=f"Mean = £{rev.mean():,.0f}")
    ax.axvline(rev.median(), color="#FF8F00", linestyle="--", linewidth=1.5,
               label=f"Median = £{rev.median():,.0f}")
    ax.set_xlabel("Total Revenue per Customer (£)", fontsize=10)
    ax.set_ylabel("Number of Customers", fontsize=10)
    ax.set_title("Customer Revenue Distribution (Linear)", fontsize=11, fontweight="bold")
    ax.xaxis.set_major_formatter(mticker.FuncFormatter(lambda v, _: f"£{v:,.0f}"))
    ax.legend(fontsize=9)
    ax.grid(alpha=0.3)

    # Log scale
    ax2 = axes[1]
    log_rev = np.log10(rev)
    ax2.hist(log_rev, bins=50, color="#C62828", edgecolor="white", alpha=0.8)
    ax2.set_xlabel("log₁₀(Total Revenue per Customer) [£]", fontsize=10)
    ax2.set_ylabel("Number of Customers", fontsize=10)
    ax2.set_title("Customer Revenue Distribution (Log Scale)\nReveals the long tail",
                  fontsize=11, fontweight="bold")
    ax2.grid(alpha=0.3)

    p90 = rev.quantile(0.90)
    p99 = rev.quantile(0.99)
    pct_gt_1000 = (rev > 1000).mean() * 100
    stats_text = (f"Top 10%: ≥ £{p90:,.0f}\n"
                  f"Top 1%: ≥ £{p99:,.0f}\n"
                  f"Customers > £1k: {pct_gt_1000:.1f}%")
    ax2.text(0.97, 0.95, stats_text, transform=ax2.transAxes, fontsize=9,
             va="top", ha="right", bbox=dict(boxstyle="round", facecolor="white", alpha=0.8))

    fig.suptitle("Customer Lifetime Revenue Distribution — Heavy-Tailed",
                 fontsize=13, fontweight="bold")
    fig.tight_layout()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    LOGGER.info("Customer value distribution → '%s'", str(output_path))


def run(args: argparse.Namespace | None = None) -> None:
    if args is None:
        args = parse_args()
    setup_logging(args.log_level)

    for p, label in [(args.transactions_path, "transactions"), (args.features_path, "features")]:
        if not Path(p).exists():
            raise FileNotFoundError(f"Required input missing: {p}. Run the pipeline first.")

    LOGGER.info("Loading data...")
    txn = pd.read_parquet(args.transactions_path)
    features = pd.read_parquet(args.features_path)

    LOGGER.info("Running Pareto analysis on %d customers...", len(features))
    pareto_stats = pareto_analysis(features)

    LOGGER.info(
        "Pareto: %.0f%% of customers → 80%% revenue | Top 10%% → %.0f%% revenue | Gini=%.3f",
        pareto_stats["pct_customers_for_80pct_revenue"],
        pareto_stats["pct_revenue_top_10pct_customers"],
        pareto_stats["gini_coefficient"],
    )

    # Save summary table
    summary_df = pd.DataFrame([{
        "metric": "pct_customers_for_80pct_revenue",
        "value": pareto_stats["pct_customers_for_80pct_revenue"],
        "interpretation": "% of customers who generate 80% of total revenue",
    }, {
        "metric": "pct_revenue_top_10pct_customers",
        "value": pareto_stats["pct_revenue_top_10pct_customers"],
        "interpretation": "% of revenue generated by the top 10% of customers",
    }, {
        "metric": "gini_coefficient",
        "value": pareto_stats["gini_coefficient"],
        "interpretation": "Revenue inequality (0=equal, 1=fully concentrated)",
    }, {
        "metric": "n_customers",
        "value": pareto_stats["n_customers"],
        "interpretation": "Total unique customers analyzed",
    }, {
        "metric": "total_revenue_gbp",
        "value": round(pareto_stats["total_revenue"], 2),
        "interpretation": "Total revenue across all customers",
    }])
    pareto_path = Path("reports/tables/pareto_summary.csv")
    pareto_path.parent.mkdir(parents=True, exist_ok=True)
    summary_df.to_csv(pareto_path, index=False)
    LOGGER.info("Pareto summary → '%s'", str(pareto_path))

    # Figures
    plot_revenue_concentration(pareto_stats, Path("reports/figures/revenue_concentration_curve.png"))
    plot_monthly_revenue(txn, Path("reports/figures/monthly_revenue_trend.png"))
    plot_customer_value_distribution(features, Path("reports/figures/customer_value_distribution.png"))

    LOGGER.info("Business insights complete.")


def main() -> None:
    run(parse_args())


if __name__ == "__main__":
    main()
